version: 2.1

executors:
  esplinux-bootstrap:
    docker:
      - image: esplinux/bootstrap
    environment:
      VERSION: "0.01"

jobs:
  zlib:
    executor: esplinux-bootstrap
    steps:
      - checkout
      - run:
          name: Build
          shell: /bin/sh -e
          command: |
            esp add ghr espbuild
            echo gnu >> /etc/esp-repos
            espbuild zlib.conf
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/package

workflows:
  build:
    jobs:
      - zlib
